extends: 'eslint:recommended'
env:
  es6: true
  node: true
globals:
  atom: true
  Audio: true
  document: true
  window: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-var:
    - error
  prefer-const:
    - error
  prefer-spread:
    - error
  quotes:
    - error
    - double
  semi:
    - error
    - always
